# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Brew.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(929, 763)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 886, 721))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 431, 691))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Brewer_name_txt = QtGui.QLineEdit(self.groupBox)
        self.Brewer_name_txt.setGeometry(QtCore.QRect(15, 20, 241, 16))
        self.Brewer_name_txt.setObjectName(_fromUtf8("Brewer_name_txt"))
        self.Brewer_label = QtGui.QLabel(self.groupBox)
        self.Brewer_label.setGeometry(QtCore.QRect(15, 0, 181, 21))
        self.Brewer_label.setObjectName(_fromUtf8("Brewer_label"))
        self.Brew_Date_txt = QtGui.QLineEdit(self.groupBox)
        self.Brew_Date_txt.setGeometry(QtCore.QRect(15, 50, 241, 16))
        self.Brew_Date_txt.setObjectName(_fromUtf8("Brew_Date_txt"))
        self.Brew_Date_label = QtGui.QLabel(self.groupBox)
        self.Brew_Date_label.setGeometry(QtCore.QRect(15, 30, 181, 21))
        self.Brew_Date_label.setObjectName(_fromUtf8("Brew_Date_label"))
        self.Batch_size_txt = QtGui.QLineEdit(self.groupBox)
        self.Batch_size_txt.setGeometry(QtCore.QRect(15, 85, 241, 16))
        self.Batch_size_txt.setObjectName(_fromUtf8("Batch_size_txt"))
        self.Batch_size_label = QtGui.QLabel(self.groupBox)
        self.Batch_size_label.setGeometry(QtCore.QRect(15, 65, 181, 21))
        self.Batch_size_label.setObjectName(_fromUtf8("Batch_size_label"))
        self.boil_time_txt = QtGui.QLineEdit(self.groupBox)
        self.boil_time_txt.setGeometry(QtCore.QRect(15, 115, 241, 16))
        self.boil_time_txt.setObjectName(_fromUtf8("boil_time_txt"))
        self.Boil_time_label = QtGui.QLabel(self.groupBox)
        self.Boil_time_label.setGeometry(QtCore.QRect(15, 95, 181, 21))
        self.Boil_time_label.setObjectName(_fromUtf8("Boil_time_label"))
        self.Ingredient_one = QtGui.QLineEdit(self.groupBox)
        self.Ingredient_one.setGeometry(QtCore.QRect(15, 175, 231, 16))
        self.Ingredient_one.setObjectName(_fromUtf8("Ingredient_one"))
        self.Ingredients = QtGui.QLabel(self.groupBox)
        self.Ingredients.setGeometry(QtCore.QRect(10, 130, 251, 41))
        self.Ingredients.setObjectName(_fromUtf8("Ingredients"))
        self.Ingredients_type_label = QtGui.QLabel(self.groupBox)
        self.Ingredients_type_label.setGeometry(QtCore.QRect(15, 160, 57, 14))
        self.Ingredients_type_label.setObjectName(_fromUtf8("Ingredients_type_label"))
        self.Amount_one = QtGui.QLineEdit(self.groupBox)
        self.Amount_one.setGeometry(QtCore.QRect(255, 175, 141, 16))
        self.Amount_one.setObjectName(_fromUtf8("Amount_one"))
        self.Ingredients_amount_label = QtGui.QLabel(self.groupBox)
        self.Ingredients_amount_label.setGeometry(QtCore.QRect(255, 160, 57, 14))
        self.Ingredients_amount_label.setObjectName(_fromUtf8("Ingredients_amount_label"))
        self.Ingredient_three = QtGui.QLineEdit(self.groupBox)
        self.Ingredient_three.setGeometry(QtCore.QRect(15, 205, 231, 16))
        self.Ingredient_three.setObjectName(_fromUtf8("Ingredient_three"))
        self.Amount_three = QtGui.QLineEdit(self.groupBox)
        self.Amount_three.setGeometry(QtCore.QRect(255, 205, 141, 16))
        self.Amount_three.setObjectName(_fromUtf8("Amount_three"))
        self.Ingredient_two = QtGui.QLineEdit(self.groupBox)
        self.Ingredient_two.setGeometry(QtCore.QRect(15, 190, 231, 16))
        self.Ingredient_two.setObjectName(_fromUtf8("Ingredient_two"))
        self.Amount_two = QtGui.QLineEdit(self.groupBox)
        self.Amount_two.setGeometry(QtCore.QRect(255, 190, 141, 16))
        self.Amount_two.setObjectName(_fromUtf8("Amount_two"))
        self.Ingredient_four = QtGui.QLineEdit(self.groupBox)
        self.Ingredient_four.setGeometry(QtCore.QRect(15, 220, 231, 16))
        self.Ingredient_four.setObjectName(_fromUtf8("Ingredient_four"))
        self.Amount_four = QtGui.QLineEdit(self.groupBox)
        self.Amount_four.setGeometry(QtCore.QRect(255, 220, 141, 16))
        self.Amount_four.setObjectName(_fromUtf8("Amount_four"))
        self.Ingredient_five = QtGui.QLineEdit(self.groupBox)
        self.Ingredient_five.setGeometry(QtCore.QRect(15, 235, 231, 16))
        self.Ingredient_five.setObjectName(_fromUtf8("Ingredient_five"))
        self.Amount_five = QtGui.QLineEdit(self.groupBox)
        self.Amount_five.setGeometry(QtCore.QRect(255, 235, 141, 16))
        self.Amount_five.setObjectName(_fromUtf8("Amount_five"))
        self.Hops_label = QtGui.QLabel(self.groupBox)
        self.Hops_label.setGeometry(QtCore.QRect(15, 250, 221, 41))
        self.Hops_label.setObjectName(_fromUtf8("Hops_label"))
        self.Amount_of_hops_label = QtGui.QLabel(self.groupBox)
        self.Amount_of_hops_label.setGeometry(QtCore.QRect(225, 280, 57, 14))
        self.Amount_of_hops_label.setObjectName(_fromUtf8("Amount_of_hops_label"))
        self.Hop_type = QtGui.QLabel(self.groupBox)
        self.Hop_type.setGeometry(QtCore.QRect(15, 280, 57, 14))
        self.Hop_type.setObjectName(_fromUtf8("Hop_type"))
        self.AA_label = QtGui.QLabel(self.groupBox)
        self.AA_label.setGeometry(QtCore.QRect(295, 280, 21, 16))
        self.AA_label.setObjectName(_fromUtf8("AA_label"))
        self.Hop_boil_time_label = QtGui.QLabel(self.groupBox)
        self.Hop_boil_time_label.setGeometry(QtCore.QRect(345, 280, 57, 14))
        self.Hop_boil_time_label.setObjectName(_fromUtf8("Hop_boil_time_label"))
        self.Hop_one = QtGui.QLineEdit(self.groupBox)
        self.Hop_one.setGeometry(QtCore.QRect(15, 295, 201, 16))
        self.Hop_one.setObjectName(_fromUtf8("Hop_one"))
        self.hop_amount_one = QtGui.QLineEdit(self.groupBox)
        self.hop_amount_one.setGeometry(QtCore.QRect(225, 295, 51, 16))
        self.hop_amount_one.setObjectName(_fromUtf8("hop_amount_one"))
        self.hop_AA_one = QtGui.QLineEdit(self.groupBox)
        self.hop_AA_one.setGeometry(QtCore.QRect(285, 295, 51, 16))
        self.hop_AA_one.setObjectName(_fromUtf8("hop_AA_one"))
        self.hop_boil_one = QtGui.QLineEdit(self.groupBox)
        self.hop_boil_one.setGeometry(QtCore.QRect(345, 295, 51, 16))
        self.hop_boil_one.setObjectName(_fromUtf8("hop_boil_one"))
        self.hop_amount_two = QtGui.QLineEdit(self.groupBox)
        self.hop_amount_two.setGeometry(QtCore.QRect(225, 310, 51, 16))
        self.hop_amount_two.setObjectName(_fromUtf8("hop_amount_two"))
        self.hop_boil_two = QtGui.QLineEdit(self.groupBox)
        self.hop_boil_two.setGeometry(QtCore.QRect(345, 310, 51, 16))
        self.hop_boil_two.setObjectName(_fromUtf8("hop_boil_two"))
        self.hop_AA_two = QtGui.QLineEdit(self.groupBox)
        self.hop_AA_two.setGeometry(QtCore.QRect(285, 310, 51, 16))
        self.hop_AA_two.setObjectName(_fromUtf8("hop_AA_two"))
        self.hop_two = QtGui.QLineEdit(self.groupBox)
        self.hop_two.setGeometry(QtCore.QRect(15, 310, 201, 16))
        self.hop_two.setObjectName(_fromUtf8("hop_two"))
        self.hop_amount_three = QtGui.QLineEdit(self.groupBox)
        self.hop_amount_three.setGeometry(QtCore.QRect(225, 325, 51, 16))
        self.hop_amount_three.setObjectName(_fromUtf8("hop_amount_three"))
        self.hop_boil_three = QtGui.QLineEdit(self.groupBox)
        self.hop_boil_three.setGeometry(QtCore.QRect(345, 325, 51, 16))
        self.hop_boil_three.setObjectName(_fromUtf8("hop_boil_three"))
        self.hop_AA_three = QtGui.QLineEdit(self.groupBox)
        self.hop_AA_three.setGeometry(QtCore.QRect(285, 325, 51, 16))
        self.hop_AA_three.setObjectName(_fromUtf8("hop_AA_three"))
        self.hop_3 = QtGui.QLineEdit(self.groupBox)
        self.hop_3.setGeometry(QtCore.QRect(15, 325, 201, 16))
        self.hop_3.setObjectName(_fromUtf8("hop_3"))
        self.hop_amount_four = QtGui.QLineEdit(self.groupBox)
        self.hop_amount_four.setGeometry(QtCore.QRect(225, 340, 51, 16))
        self.hop_amount_four.setObjectName(_fromUtf8("hop_amount_four"))
        self.hop_boil_four = QtGui.QLineEdit(self.groupBox)
        self.hop_boil_four.setGeometry(QtCore.QRect(345, 340, 51, 16))
        self.hop_boil_four.setObjectName(_fromUtf8("hop_boil_four"))
        self.hop_AA_four = QtGui.QLineEdit(self.groupBox)
        self.hop_AA_four.setGeometry(QtCore.QRect(285, 340, 51, 16))
        self.hop_AA_four.setObjectName(_fromUtf8("hop_AA_four"))
        self.hop_4 = QtGui.QLineEdit(self.groupBox)
        self.hop_4.setGeometry(QtCore.QRect(15, 340, 201, 16))
        self.hop_4.setObjectName(_fromUtf8("hop_4"))
        self.hop_amount_five = QtGui.QLineEdit(self.groupBox)
        self.hop_amount_five.setGeometry(QtCore.QRect(225, 355, 51, 16))
        self.hop_amount_five.setObjectName(_fromUtf8("hop_amount_five"))
        self.hop_boil_five = QtGui.QLineEdit(self.groupBox)
        self.hop_boil_five.setGeometry(QtCore.QRect(345, 355, 51, 16))
        self.hop_boil_five.setObjectName(_fromUtf8("hop_boil_five"))
        self.hop_AA_five = QtGui.QLineEdit(self.groupBox)
        self.hop_AA_five.setGeometry(QtCore.QRect(285, 355, 51, 16))
        self.hop_AA_five.setObjectName(_fromUtf8("hop_AA_five"))
        self.hop_five = QtGui.QLineEdit(self.groupBox)
        self.hop_five.setGeometry(QtCore.QRect(15, 355, 201, 16))
        self.hop_five.setObjectName(_fromUtf8("hop_five"))
        self.Batch_vital_label = QtGui.QLabel(self.groupBox)
        self.Batch_vital_label.setGeometry(QtCore.QRect(15, 370, 271, 41))
        self.Batch_vital_label.setObjectName(_fromUtf8("Batch_vital_label"))
        self.original_gravity_label = QtGui.QLabel(self.groupBox)
        self.original_gravity_label.setGeometry(QtCore.QRect(15, 400, 211, 16))
        self.original_gravity_label.setObjectName(_fromUtf8("original_gravity_label"))
        self.final_gravity_label = QtGui.QLabel(self.groupBox)
        self.final_gravity_label.setGeometry(QtCore.QRect(15, 415, 211, 16))
        self.final_gravity_label.setObjectName(_fromUtf8("final_gravity_label"))
        self.Alcohol_volume_label = QtGui.QLabel(self.groupBox)
        self.Alcohol_volume_label.setGeometry(QtCore.QRect(15, 430, 241, 16))
        self.Alcohol_volume_label.setObjectName(_fromUtf8("Alcohol_volume_label"))
        self.IBU_label = QtGui.QLabel(self.groupBox)
        self.IBU_label.setGeometry(QtCore.QRect(15, 445, 211, 16))
        self.IBU_label.setObjectName(_fromUtf8("IBU_label"))
        self.SRM_label = QtGui.QLabel(self.groupBox)
        self.SRM_label.setGeometry(QtCore.QRect(15, 460, 211, 16))
        self.SRM_label.setObjectName(_fromUtf8("SRM_label"))
        self.Brewhouse_efficiency_label = QtGui.QLabel(self.groupBox)
        self.Brewhouse_efficiency_label.setGeometry(QtCore.QRect(15, 475, 211, 16))
        self.Brewhouse_efficiency_label.setObjectName(_fromUtf8("Brewhouse_efficiency_label"))
        self.Carbonation_level_label = QtGui.QLabel(self.groupBox)
        self.Carbonation_level_label.setGeometry(QtCore.QRect(15, 490, 211, 16))
        self.Carbonation_level_label.setObjectName(_fromUtf8("Carbonation_level_label"))
        self.Hydrometer_Reading_label = QtGui.QLabel(self.groupBox)
        self.Hydrometer_Reading_label.setGeometry(QtCore.QRect(15, 505, 381, 41))
        self.Hydrometer_Reading_label.setObjectName(_fromUtf8("Hydrometer_Reading_label"))
        self.hydrometer_racked_label = QtGui.QLabel(self.groupBox)
        self.hydrometer_racked_label.setGeometry(QtCore.QRect(10, 580, 71, 16))
        self.hydrometer_racked_label.setObjectName(_fromUtf8("hydrometer_racked_label"))
        self.hydrometer_preboil_label = QtGui.QLabel(self.groupBox)
        self.hydrometer_preboil_label.setGeometry(QtCore.QRect(10, 550, 71, 16))
        self.hydrometer_preboil_label.setObjectName(_fromUtf8("hydrometer_preboil_label"))
        self.hydrometer_afterboil_label = QtGui.QLabel(self.groupBox)
        self.hydrometer_afterboil_label.setGeometry(QtCore.QRect(10, 565, 91, 16))
        self.hydrometer_afterboil_label.setObjectName(_fromUtf8("hydrometer_afterboil_label"))
        self.hydrometer_final_label = QtGui.QLabel(self.groupBox)
        self.hydrometer_final_label.setGeometry(QtCore.QRect(10, 595, 71, 16))
        self.hydrometer_final_label.setObjectName(_fromUtf8("hydrometer_final_label"))
        self.Hydrometer_date_label = QtGui.QLabel(self.groupBox)
        self.Hydrometer_date_label.setGeometry(QtCore.QRect(170, 535, 71, 21))
        self.Hydrometer_date_label.setObjectName(_fromUtf8("Hydrometer_date_label"))
        self.Hydrometer_gravity_label = QtGui.QLabel(self.groupBox)
        self.Hydrometer_gravity_label.setGeometry(QtCore.QRect(285, 535, 91, 21))
        self.Hydrometer_gravity_label.setObjectName(_fromUtf8("Hydrometer_gravity_label"))
        self.original_gravity_txt = QtGui.QLineEdit(self.groupBox)
        self.original_gravity_txt.setGeometry(QtCore.QRect(225, 400, 201, 16))
        self.original_gravity_txt.setObjectName(_fromUtf8("original_gravity_txt"))
        self.final_gravity_txt = QtGui.QLineEdit(self.groupBox)
        self.final_gravity_txt.setGeometry(QtCore.QRect(225, 415, 201, 16))
        self.final_gravity_txt.setObjectName(_fromUtf8("final_gravity_txt"))
        self.Alcohol_volume_txt = QtGui.QLineEdit(self.groupBox)
        self.Alcohol_volume_txt.setGeometry(QtCore.QRect(225, 430, 196, 16))
        self.Alcohol_volume_txt.setObjectName(_fromUtf8("Alcohol_volume_txt"))
        self.IBU_txt = QtGui.QLineEdit(self.groupBox)
        self.IBU_txt.setGeometry(QtCore.QRect(225, 445, 201, 16))
        self.IBU_txt.setObjectName(_fromUtf8("IBU_txt"))
        self.SRM_txt = QtGui.QLineEdit(self.groupBox)
        self.SRM_txt.setGeometry(QtCore.QRect(225, 460, 201, 16))
        self.SRM_txt.setObjectName(_fromUtf8("SRM_txt"))
        self.Brewhouse_efficiency_txt = QtGui.QLineEdit(self.groupBox)
        self.Brewhouse_efficiency_txt.setGeometry(QtCore.QRect(225, 475, 201, 16))
        self.Brewhouse_efficiency_txt.setObjectName(_fromUtf8("Brewhouse_efficiency_txt"))
        self.Carbonation_level_txt = QtGui.QLineEdit(self.groupBox)
        self.Carbonation_level_txt.setGeometry(QtCore.QRect(225, 490, 201, 16))
        self.Carbonation_level_txt.setObjectName(_fromUtf8("Carbonation_level_txt"))
        self.hydrometer_preboil_date_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_preboil_date_txt.setGeometry(QtCore.QRect(135, 550, 111, 16))
        self.hydrometer_preboil_date_txt.setObjectName(_fromUtf8("hydrometer_preboil_date_txt"))
        self.hydrometer_afterboil_date_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_afterboil_date_txt.setGeometry(QtCore.QRect(135, 565, 111, 16))
        self.hydrometer_afterboil_date_txt.setObjectName(_fromUtf8("hydrometer_afterboil_date_txt"))
        self.hydrometer_racked_date_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_racked_date_txt.setGeometry(QtCore.QRect(135, 580, 111, 16))
        self.hydrometer_racked_date_txt.setObjectName(_fromUtf8("hydrometer_racked_date_txt"))
        self.hydrometer_final_date_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_final_date_txt.setGeometry(QtCore.QRect(135, 595, 111, 16))
        self.hydrometer_final_date_txt.setObjectName(_fromUtf8("hydrometer_final_date_txt"))
        self.hydrometer_preboil_gravity_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_preboil_gravity_txt.setGeometry(QtCore.QRect(255, 550, 111, 16))
        self.hydrometer_preboil_gravity_txt.setObjectName(_fromUtf8("hydrometer_preboil_gravity_txt"))
        self.hydrometer_racked_gravity_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_racked_gravity_txt.setGeometry(QtCore.QRect(255, 580, 111, 16))
        self.hydrometer_racked_gravity_txt.setObjectName(_fromUtf8("hydrometer_racked_gravity_txt"))
        self.hydrometer_final_gravity_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_final_gravity_txt.setGeometry(QtCore.QRect(255, 595, 111, 16))
        self.hydrometer_final_gravity_txt.setObjectName(_fromUtf8("hydrometer_final_gravity_txt"))
        self.hydrometer_afterboil_gravity_txt = QtGui.QLineEdit(self.groupBox)
        self.hydrometer_afterboil_gravity_txt.setGeometry(QtCore.QRect(255, 565, 111, 16))
        self.hydrometer_afterboil_gravity_txt.setObjectName(_fromUtf8("hydrometer_afterboil_gravity_txt"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(435, 0, 436, 691))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Recipe_name_txt = QtGui.QLineEdit(self.groupBox_2)
        self.Recipe_name_txt.setGeometry(QtCore.QRect(15, 20, 241, 16))
        self.Recipe_name_txt.setObjectName(_fromUtf8("Recipe_name_txt"))
        self.recipe_name_label = QtGui.QLabel(self.groupBox_2)
        self.recipe_name_label.setGeometry(QtCore.QRect(15, 0, 181, 21))
        self.recipe_name_label.setObjectName(_fromUtf8("recipe_name_label"))
        self.beer_type_txt = QtGui.QLineEdit(self.groupBox_2)
        self.beer_type_txt.setGeometry(QtCore.QRect(15, 60, 241, 16))
        self.beer_type_txt.setObjectName(_fromUtf8("beer_type_txt"))
        self.beer_type_label = QtGui.QLabel(self.groupBox_2)
        self.beer_type_label.setGeometry(QtCore.QRect(15, 40, 181, 21))
        self.beer_type_label.setObjectName(_fromUtf8("beer_type_label"))
        self.Batch_txt = QtGui.QLineEdit(self.groupBox_2)
        self.Batch_txt.setGeometry(QtCore.QRect(15, 90, 241, 16))
        self.Batch_txt.setObjectName(_fromUtf8("Batch_txt"))
        self.Batchnumber_label = QtGui.QLabel(self.groupBox_2)
        self.Batchnumber_label.setGeometry(QtCore.QRect(15, 70, 181, 21))
        self.Batchnumber_label.setObjectName(_fromUtf8("Batchnumber_label"))
        self.efficiency_txt = QtGui.QLineEdit(self.groupBox_2)
        self.efficiency_txt.setGeometry(QtCore.QRect(15, 125, 241, 16))
        self.efficiency_txt.setObjectName(_fromUtf8("efficiency_txt"))
        self.efficiency_label = QtGui.QLabel(self.groupBox_2)
        self.efficiency_label.setGeometry(QtCore.QRect(15, 105, 181, 21))
        self.efficiency_label.setObjectName(_fromUtf8("efficiency_label"))
        self.infusion_one_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_one_txt.setGeometry(QtCore.QRect(15, 180, 231, 16))
        self.infusion_one_txt.setObjectName(_fromUtf8("infusion_one_txt"))
        self.Mash_schedule_label = QtGui.QLabel(self.groupBox_2)
        self.Mash_schedule_label.setGeometry(QtCore.QRect(15, 135, 251, 41))
        self.Mash_schedule_label.setObjectName(_fromUtf8("Mash_schedule_label"))
        self.infusion_amount_label = QtGui.QLabel(self.groupBox_2)
        self.infusion_amount_label.setGeometry(QtCore.QRect(15, 165, 131, 16))
        self.infusion_amount_label.setObjectName(_fromUtf8("infusion_amount_label"))
        self.infusion_temp_one_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_temp_one_txt.setGeometry(QtCore.QRect(255, 180, 51, 16))
        self.infusion_temp_one_txt.setObjectName(_fromUtf8("infusion_temp_one_txt"))
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(255, 165, 57, 14))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.infusion_three_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_three_txt.setGeometry(QtCore.QRect(15, 210, 231, 16))
        self.infusion_three_txt.setObjectName(_fromUtf8("infusion_three_txt"))
        self.infusion_temp_three_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_temp_three_txt.setGeometry(QtCore.QRect(255, 210, 51, 16))
        self.infusion_temp_three_txt.setObjectName(_fromUtf8("infusion_temp_three_txt"))
        self.infusion_two_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_two_txt.setGeometry(QtCore.QRect(15, 195, 231, 16))
        self.infusion_two_txt.setObjectName(_fromUtf8("infusion_two_txt"))
        self.infusion_temp_two_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_temp_two_txt.setGeometry(QtCore.QRect(255, 195, 51, 16))
        self.infusion_temp_two_txt.setObjectName(_fromUtf8("infusion_temp_two_txt"))
        self.infusion_four_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_four_txt.setGeometry(QtCore.QRect(15, 225, 231, 16))
        self.infusion_four_txt.setObjectName(_fromUtf8("infusion_four_txt"))
        self.infusion_temp_four_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_temp_four_txt.setGeometry(QtCore.QRect(255, 225, 51, 16))
        self.infusion_temp_four_txt.setObjectName(_fromUtf8("infusion_temp_four_txt"))
        self.infusion_five_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_five_txt.setGeometry(QtCore.QRect(15, 240, 231, 16))
        self.infusion_five_txt.setObjectName(_fromUtf8("infusion_five_txt"))
        self.infusion_temp_five_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_temp_five_txt.setGeometry(QtCore.QRect(255, 240, 51, 16))
        self.infusion_temp_five_txt.setObjectName(_fromUtf8("infusion_temp_five_txt"))
        self.Yeast_label = QtGui.QLabel(self.groupBox_2)
        self.Yeast_label.setGeometry(QtCore.QRect(15, 255, 221, 41))
        self.Yeast_label.setObjectName(_fromUtf8("Yeast_label"))
        self.cost_label = QtGui.QLabel(self.groupBox_2)
        self.cost_label.setGeometry(QtCore.QRect(15, 330, 81, 41))
        self.cost_label.setObjectName(_fromUtf8("cost_label"))
        self.cost_grains_label = QtGui.QLabel(self.groupBox_2)
        self.cost_grains_label.setGeometry(QtCore.QRect(15, 360, 211, 16))
        self.cost_grains_label.setObjectName(_fromUtf8("cost_grains_label"))
        self.cost_hops_label = QtGui.QLabel(self.groupBox_2)
        self.cost_hops_label.setGeometry(QtCore.QRect(15, 375, 211, 16))
        self.cost_hops_label.setObjectName(_fromUtf8("cost_hops_label"))
        self.cost_yeast_label = QtGui.QLabel(self.groupBox_2)
        self.cost_yeast_label.setGeometry(QtCore.QRect(15, 390, 241, 16))
        self.cost_yeast_label.setObjectName(_fromUtf8("cost_yeast_label"))
        self.cost_other_label = QtGui.QLabel(self.groupBox_2)
        self.cost_other_label.setGeometry(QtCore.QRect(15, 405, 211, 16))
        self.cost_other_label.setObjectName(_fromUtf8("cost_other_label"))
        self.cost_grains_txt = QtGui.QLineEdit(self.groupBox_2)
        self.cost_grains_txt.setGeometry(QtCore.QRect(255, 360, 161, 16))
        self.cost_grains_txt.setObjectName(_fromUtf8("cost_grains_txt"))
        self.cost_grains_txt_2 = QtGui.QLineEdit(self.groupBox_2)
        self.cost_grains_txt_2.setGeometry(QtCore.QRect(255, 375, 161, 16))
        self.cost_grains_txt_2.setObjectName(_fromUtf8("cost_grains_txt_2"))
        self.cost_yeast_txt = QtGui.QLineEdit(self.groupBox_2)
        self.cost_yeast_txt.setGeometry(QtCore.QRect(255, 390, 161, 16))
        self.cost_yeast_txt.setObjectName(_fromUtf8("cost_yeast_txt"))
        self.cost_other_txt = QtGui.QLineEdit(self.groupBox_2)
        self.cost_other_txt.setGeometry(QtCore.QRect(255, 405, 161, 16))
        self.cost_other_txt.setObjectName(_fromUtf8("cost_other_txt"))
        self.infusion_time_one_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_time_one_txt.setGeometry(QtCore.QRect(315, 180, 51, 16))
        self.infusion_time_one_txt.setObjectName(_fromUtf8("infusion_time_one_txt"))
        self.label_55 = QtGui.QLabel(self.groupBox_2)
        self.label_55.setGeometry(QtCore.QRect(315, 165, 57, 14))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.infusion_time_four_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_time_four_txt.setGeometry(QtCore.QRect(315, 225, 51, 16))
        self.infusion_time_four_txt.setObjectName(_fromUtf8("infusion_time_four_txt"))
        self.infusion_time_five_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_time_five_txt.setGeometry(QtCore.QRect(315, 240, 51, 16))
        self.infusion_time_five_txt.setObjectName(_fromUtf8("infusion_time_five_txt"))
        self.infusion_time_two_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_time_two_txt.setGeometry(QtCore.QRect(315, 195, 51, 16))
        self.infusion_time_two_txt.setObjectName(_fromUtf8("infusion_time_two_txt"))
        self.infusion_time_three_txt = QtGui.QLineEdit(self.groupBox_2)
        self.infusion_time_three_txt.setGeometry(QtCore.QRect(315, 210, 51, 16))
        self.infusion_time_three_txt.setObjectName(_fromUtf8("infusion_time_three_txt"))
        self.yeat_starter_txt = QtGui.QLineEdit(self.groupBox_2)
        self.yeat_starter_txt.setGeometry(QtCore.QRect(165, 315, 261, 16))
        self.yeat_starter_txt.setObjectName(_fromUtf8("yeat_starter_txt"))
        self.yeast_starter_label = QtGui.QLabel(self.groupBox_2)
        self.yeast_starter_label.setGeometry(QtCore.QRect(15, 315, 241, 16))
        self.yeast_starter_label.setObjectName(_fromUtf8("yeast_starter_label"))
        self.yeast_type_label = QtGui.QLabel(self.groupBox_2)
        self.yeast_type_label.setGeometry(QtCore.QRect(15, 285, 211, 16))
        self.yeast_type_label.setObjectName(_fromUtf8("yeast_type_label"))
        self.yeast_attenuation_label = QtGui.QLabel(self.groupBox_2)
        self.yeast_attenuation_label.setGeometry(QtCore.QRect(15, 300, 211, 16))
        self.yeast_attenuation_label.setObjectName(_fromUtf8("yeast_attenuation_label"))
        self.yeast_attenuation_txt = QtGui.QLineEdit(self.groupBox_2)
        self.yeast_attenuation_txt.setGeometry(QtCore.QRect(165, 300, 261, 16))
        self.yeast_attenuation_txt.setObjectName(_fromUtf8("yeast_attenuation_txt"))
        self.yeast_type_txt = QtGui.QLineEdit(self.groupBox_2)
        self.yeast_type_txt.setGeometry(QtCore.QRect(165, 285, 261, 16))
        self.yeast_type_txt.setObjectName(_fromUtf8("yeast_type_txt"))
        self.dollar_sign = QtGui.QLabel(self.groupBox_2)
        self.dollar_sign.setGeometry(QtCore.QRect(265, 330, 81, 41))
        self.dollar_sign.setObjectName(_fromUtf8("dollar_sign"))
        self.cost_total_label = QtGui.QLabel(self.groupBox_2)
        self.cost_total_label.setGeometry(QtCore.QRect(195, 420, 211, 16))
        self.cost_total_label.setObjectName(_fromUtf8("cost_total_label"))
        self.cost_total_txt = QtGui.QLineEdit(self.groupBox_2)
        self.cost_total_txt.setGeometry(QtCore.QRect(255, 420, 161, 16))
        self.cost_total_txt.setObjectName(_fromUtf8("cost_total_txt"))
        self.notes_label = QtGui.QLabel(self.groupBox_2)
        self.notes_label.setGeometry(QtCore.QRect(15, 420, 81, 41))
        self.notes_label.setObjectName(_fromUtf8("notes_label"))
        self.Notes = QtGui.QTextEdit(self.groupBox_2)
        self.Notes.setGeometry(QtCore.QRect(15, 450, 411, 211))
        self.Notes.setObjectName(_fromUtf8("Notes"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 331, 551))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.HLT_TEMP = QtGui.QLCDNumber(self.frame)
        self.HLT_TEMP.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.HLT_TEMP.setObjectName(_fromUtf8("HLT_TEMP"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 101, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.MASH_TEMP = QtGui.QLCDNumber(self.frame)
        self.MASH_TEMP.setGeometry(QtCore.QRect(80, 30, 71, 31))
        self.MASH_TEMP.setObjectName(_fromUtf8("MASH_TEMP"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 101, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Boil_TEMP = QtGui.QLCDNumber(self.frame)
        self.Boil_TEMP.setGeometry(QtCore.QRect(150, 30, 71, 31))
        self.Boil_TEMP.setObjectName(_fromUtf8("Boil_TEMP"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(230, 10, 101, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Chiller_TEMP = QtGui.QLCDNumber(self.frame)
        self.Chiller_TEMP.setGeometry(QtCore.QRect(220, 30, 71, 31))
        self.Chiller_TEMP.setObjectName(_fromUtf8("Chiller_TEMP"))
        self.ALARM_HLT_1 = QtGui.QTimeEdit(self.frame)
        self.ALARM_HLT_1.setGeometry(QtCore.QRect(10, 230, 91, 31))
        self.ALARM_HLT_1.setObjectName(_fromUtf8("ALARM_HLT_1"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 91, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.HLT_alarm_set1 = QtGui.QCheckBox(self.frame)
        self.HLT_alarm_set1.setGeometry(QtCore.QRect(10, 200, 100, 31))
        self.HLT_alarm_set1.setObjectName(_fromUtf8("HLT_alarm_set1"))
        self.HLT_TIMER_SET = QtGui.QTimeEdit(self.frame)
        self.HLT_TIMER_SET.setGeometry(QtCore.QRect(10, 140, 101, 31))
        self.HLT_TIMER_SET.setObjectName(_fromUtf8("HLT_TIMER_SET"))
        self.HTL_Start = QtGui.QPushButton(self.frame)
        self.HTL_Start.setGeometry(QtCore.QRect(10, 170, 83, 24))
        self.HTL_Start.setObjectName(_fromUtf8("HTL_Start"))
        self.ALARM_HLT_2 = QtGui.QTimeEdit(self.frame)
        self.ALARM_HLT_2.setGeometry(QtCore.QRect(10, 300, 91, 31))
        self.ALARM_HLT_2.setObjectName(_fromUtf8("ALARM_HLT_2"))
        self.HLT_alarm_set1_2 = QtGui.QCheckBox(self.frame)
        self.HLT_alarm_set1_2.setGeometry(QtCore.QRect(10, 270, 100, 31))
        self.HLT_alarm_set1_2.setObjectName(_fromUtf8("HLT_alarm_set1_2"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.ALARM_HLT_3 = QtGui.QTimeEdit(self.frame)
        self.ALARM_HLT_3.setGeometry(QtCore.QRect(10, 370, 81, 31))
        self.ALARM_HLT_3.setObjectName(_fromUtf8("ALARM_HLT_3"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 330, 91, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.HLT_alarm_set1_3 = QtGui.QCheckBox(self.frame)
        self.HLT_alarm_set1_3.setGeometry(QtCore.QRect(10, 340, 100, 31))
        self.HLT_alarm_set1_3.setObjectName(_fromUtf8("HLT_alarm_set1_3"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 120, 101, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.START_TIMER = QtGui.QPushButton(self.frame)
        self.START_TIMER.setGeometry(QtCore.QRect(120, 130, 83, 24))
        self.START_TIMER.setObjectName(_fromUtf8("START_TIMER"))
        self.ALARM_HLT_4 = QtGui.QTimeEdit(self.frame)
        self.ALARM_HLT_4.setGeometry(QtCore.QRect(10, 440, 91, 31))
        self.ALARM_HLT_4.setObjectName(_fromUtf8("ALARM_HLT_4"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 400, 91, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.HLT_alarm_set1_4 = QtGui.QCheckBox(self.frame)
        self.HLT_alarm_set1_4.setGeometry(QtCore.QRect(10, 410, 100, 31))
        self.HLT_alarm_set1_4.setObjectName(_fromUtf8("HLT_alarm_set1_4"))
        self.BOIL_TIMER_SET = QtGui.QTimeEdit(self.frame)
        self.BOIL_TIMER_SET.setGeometry(QtCore.QRect(220, 140, 91, 31))
        self.BOIL_TIMER_SET.setObjectName(_fromUtf8("BOIL_TIMER_SET"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(220, 120, 101, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.BOIL_TIMER_START_2 = QtGui.QPushButton(self.frame)
        self.BOIL_TIMER_START_2.setGeometry(QtCore.QRect(220, 170, 91, 24))
        self.BOIL_TIMER_START_2.setObjectName(_fromUtf8("BOIL_TIMER_START_2"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(220, 190, 91, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.Boil_alarm_set1 = QtGui.QCheckBox(self.frame)
        self.Boil_alarm_set1.setGeometry(QtCore.QRect(220, 200, 100, 31))
        self.Boil_alarm_set1.setObjectName(_fromUtf8("Boil_alarm_set1"))
        self.ALARM_BOIL_1 = QtGui.QTimeEdit(self.frame)
        self.ALARM_BOIL_1.setGeometry(QtCore.QRect(220, 230, 91, 31))
        self.ALARM_BOIL_1.setObjectName(_fromUtf8("ALARM_BOIL_1"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(220, 260, 91, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.ALARM_BOIL_2 = QtGui.QTimeEdit(self.frame)
        self.ALARM_BOIL_2.setGeometry(QtCore.QRect(220, 300, 91, 31))
        self.ALARM_BOIL_2.setObjectName(_fromUtf8("ALARM_BOIL_2"))
        self.Boil_alarm_set1_2 = QtGui.QCheckBox(self.frame)
        self.Boil_alarm_set1_2.setGeometry(QtCore.QRect(220, 270, 100, 31))
        self.Boil_alarm_set1_2.setObjectName(_fromUtf8("Boil_alarm_set1_2"))
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(220, 330, 91, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.ALARM_BOIL_3 = QtGui.QTimeEdit(self.frame)
        self.ALARM_BOIL_3.setGeometry(QtCore.QRect(220, 370, 91, 31))
        self.ALARM_BOIL_3.setObjectName(_fromUtf8("ALARM_BOIL_3"))
        self.Boil_alarm_set1_3 = QtGui.QCheckBox(self.frame)
        self.Boil_alarm_set1_3.setGeometry(QtCore.QRect(220, 340, 100, 31))
        self.Boil_alarm_set1_3.setObjectName(_fromUtf8("Boil_alarm_set1_3"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(220, 400, 91, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.Boil_alarm_set1_4 = QtGui.QCheckBox(self.frame)
        self.Boil_alarm_set1_4.setGeometry(QtCore.QRect(220, 410, 100, 31))
        self.Boil_alarm_set1_4.setObjectName(_fromUtf8("Boil_alarm_set1_4"))
        self.ALARM_BOIL_4 = QtGui.QTimeEdit(self.frame)
        self.ALARM_BOIL_4.setGeometry(QtCore.QRect(220, 440, 91, 31))
        self.ALARM_BOIL_4.setObjectName(_fromUtf8("ALARM_BOIL_4"))
        self.ALARM_HLT_5 = QtGui.QTimeEdit(self.frame)
        self.ALARM_HLT_5.setGeometry(QtCore.QRect(10, 510, 91, 31))
        self.ALARM_HLT_5.setObjectName(_fromUtf8("ALARM_HLT_5"))
        self.HLT_alarm_set1_5 = QtGui.QCheckBox(self.frame)
        self.HLT_alarm_set1_5.setGeometry(QtCore.QRect(10, 480, 100, 31))
        self.HLT_alarm_set1_5.setObjectName(_fromUtf8("HLT_alarm_set1_5"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 470, 91, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ALARM_BOIL_5 = QtGui.QTimeEdit(self.frame)
        self.ALARM_BOIL_5.setGeometry(QtCore.QRect(220, 510, 91, 31))
        self.ALARM_BOIL_5.setObjectName(_fromUtf8("ALARM_BOIL_5"))
        self.Boil_alarm_set1_5 = QtGui.QCheckBox(self.frame)
        self.Boil_alarm_set1_5.setGeometry(QtCore.QRect(220, 480, 100, 31))
        self.Boil_alarm_set1_5.setObjectName(_fromUtf8("Boil_alarm_set1_5"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(220, 470, 91, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.HLT_Timer_DISPLAY = QtGui.QLCDNumber(self.frame)
        self.HLT_Timer_DISPLAY.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.HLT_Timer_DISPLAY.setObjectName(_fromUtf8("HLT_Timer_DISPLAY"))
        self.TIMER_DISPLAY = QtGui.QLCDNumber(self.frame)
        self.TIMER_DISPLAY.setGeometry(QtCore.QRect(120, 90, 81, 31))
        self.TIMER_DISPLAY.setObjectName(_fromUtf8("TIMER_DISPLAY"))
        self.BOIL_TIMER_DISPLAY = QtGui.QLCDNumber(self.frame)
        self.BOIL_TIMER_DISPLAY.setGeometry(QtCore.QRect(220, 90, 91, 31))
        self.BOIL_TIMER_DISPLAY.setObjectName(_fromUtf8("BOIL_TIMER_DISPLAY"))
        self.STOP_TIMER = QtGui.QPushButton(self.frame)
        self.STOP_TIMER.setGeometry(QtCore.QRect(120, 160, 83, 24))
        self.STOP_TIMER.setObjectName(_fromUtf8("STOP_TIMER"))
        self.RESET_TIMER = QtGui.QPushButton(self.frame)
        self.RESET_TIMER.setGeometry(QtCore.QRect(120, 190, 83, 31))
        self.RESET_TIMER.setObjectName(_fromUtf8("RESET_TIMER"))
        self.ALARM_RESET = QtGui.QPushButton(self.frame)
        self.ALARM_RESET.setGeometry(QtCore.QRect(120, 270, 83, 61))
        self.ALARM_RESET.setObjectName(_fromUtf8("ALARM_RESET"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 0, 466, 271))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(330, 274, 466, 256))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_2 = QtGui.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 886, 541))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.Fermenter_two_temp = QtGui.QLCDNumber(self.frame_2)
        self.Fermenter_two_temp.setGeometry(QtCore.QRect(210, 0, 106, 31))
        self.Fermenter_two_temp.setObjectName(_fromUtf8("Fermenter_two_temp"))
        self.Fermenter_one_temp = QtGui.QLCDNumber(self.frame_2)
        self.Fermenter_one_temp.setGeometry(QtCore.QRect(105, 0, 106, 31))
        self.Fermenter_one_temp.setObjectName(_fromUtf8("Fermenter_one_temp"))
        self.Cooler_Temp = QtGui.QLCDNumber(self.frame_2)
        self.Cooler_Temp.setGeometry(QtCore.QRect(0, 0, 106, 31))
        self.Cooler_Temp.setObjectName(_fromUtf8("Cooler_Temp"))
        self.Fermenter_three_temp = QtGui.QLCDNumber(self.frame_2)
        self.Fermenter_three_temp.setGeometry(QtCore.QRect(315, 0, 106, 31))
        self.Fermenter_three_temp.setObjectName(_fromUtf8("Fermenter_three_temp"))
        self.Fermenter_two_label = QtGui.QLabel(self.frame_2)
        self.Fermenter_two_label.setGeometry(QtCore.QRect(225, 30, 76, 20))
        self.Fermenter_two_label.setObjectName(_fromUtf8("Fermenter_two_label"))
        self.cooler_temp_label = QtGui.QLabel(self.frame_2)
        self.cooler_temp_label.setGeometry(QtCore.QRect(0, 30, 76, 20))
        self.cooler_temp_label.setObjectName(_fromUtf8("cooler_temp_label"))
        self.fermenter_one_label = QtGui.QLabel(self.frame_2)
        self.fermenter_one_label.setGeometry(QtCore.QRect(120, 30, 76, 20))
        self.fermenter_one_label.setObjectName(_fromUtf8("fermenter_one_label"))
        self.Fermenter_three_label = QtGui.QLabel(self.frame_2)
        self.Fermenter_three_label.setGeometry(QtCore.QRect(330, 30, 76, 20))
        self.Fermenter_three_label.setObjectName(_fromUtf8("Fermenter_three_label"))
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(15, 255, 76, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 255, 76, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(225, 255, 76, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 255, 76, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.checkBox = QtGui.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(15, 285, 76, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(120, 285, 91, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(225, 285, 91, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(330, 285, 91, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.radioButton = QtGui.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(60, 345, 82, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(165, 345, 82, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_3.setGeometry(QtCore.QRect(255, 345, 82, 17))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(45, 75, 106, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 75, 106, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(255, 75, 106, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.Fermenter_three_label_2 = QtGui.QLabel(self.frame_2)
        self.Fermenter_three_label_2.setGeometry(QtCore.QRect(270, 90, 76, 20))
        self.Fermenter_three_label_2.setObjectName(_fromUtf8("Fermenter_three_label_2"))
        self.fermenter_one_label_2 = QtGui.QLabel(self.frame_2)
        self.fermenter_one_label_2.setGeometry(QtCore.QRect(60, 90, 76, 20))
        self.fermenter_one_label_2.setObjectName(_fromUtf8("fermenter_one_label_2"))
        self.Fermenter_two_label_2 = QtGui.QLabel(self.frame_2)
        self.Fermenter_two_label_2.setGeometry(QtCore.QRect(165, 90, 76, 20))
        self.Fermenter_two_label_2.setObjectName(_fromUtf8("Fermenter_two_label_2"))
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(45, 120, 106, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.Fermenter_two_label_3 = QtGui.QLabel(self.frame_2)
        self.Fermenter_two_label_3.setGeometry(QtCore.QRect(165, 135, 76, 20))
        self.Fermenter_two_label_3.setObjectName(_fromUtf8("Fermenter_two_label_3"))
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 120, 106, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.fermenter_one_label_3 = QtGui.QLabel(self.frame_2)
        self.fermenter_one_label_3.setGeometry(QtCore.QRect(60, 135, 76, 20))
        self.fermenter_one_label_3.setObjectName(_fromUtf8("fermenter_one_label_3"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(255, 120, 106, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.Fermenter_three_label_3 = QtGui.QLabel(self.frame_2)
        self.Fermenter_three_label_3.setGeometry(QtCore.QRect(270, 135, 76, 20))
        self.Fermenter_three_label_3.setObjectName(_fromUtf8("Fermenter_three_label_3"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(45, 208, 316, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(420, 0, 451, 286))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(420, 285, 451, 286))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(0, 720, 886, 30))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.Brewer_label.setText(_translate("MainWindow", "Brewer:", None))
        self.Brew_Date_label.setText(_translate("MainWindow", "Brew Date MM/DD/YY", None))
        self.Batch_size_label.setText(_translate("MainWindow", "Batch Size in Gallons", None))
        self.Boil_time_label.setText(_translate("MainWindow", "Boil Time", None))
        self.Ingredients.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Grains and Ingredients</span></p></body></html>", None))
        self.Ingredients_type_label.setText(_translate("MainWindow", "TYPE", None))
        self.Ingredients_amount_label.setText(_translate("MainWindow", "Amount", None))
        self.Hops_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Hops</span></p></body></html>", None))
        self.Amount_of_hops_label.setText(_translate("MainWindow", "Amount", None))
        self.Hop_type.setText(_translate("MainWindow", "TYPE", None))
        self.AA_label.setText(_translate("MainWindow", "AA", None))
        self.Hop_boil_time_label.setText(_translate("MainWindow", "Boil Time", None))
        self.Batch_vital_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Batch Vital Statistics:</span></p></body></html>", None))
        self.original_gravity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Expected Original Gravity</span></p></body></html>", None))
        self.final_gravity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Expected Final Gravity</span></p></body></html>", None))
        self.Alcohol_volume_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Expected Alcohol By Volume</span></p></body></html>", None))
        self.IBU_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">IBUs (bitterness)</span></p></body></html>", None))
        self.SRM_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">SRM (color)</span></p></body></html>", None))
        self.Brewhouse_efficiency_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Brew house Efficiency</span></p></body></html>", None))
        self.Carbonation_level_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Carbonation Level</span></p></body></html>", None))
        self.Hydrometer_Reading_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Hydrometer Reading - @ 60 F / 15.5 C</span></p></body></html>", None))
        self.hydrometer_racked_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Racked</span></p></body></html>", None))
        self.hydrometer_preboil_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Pre-Boil</span></p></body></html>", None))
        self.hydrometer_afterboil_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">After-Boil</span></p></body></html>", None))
        self.hydrometer_final_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Final</span></p></body></html>", None))
        self.Hydrometer_date_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Date</span></p></body></html>", None))
        self.Hydrometer_gravity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Gravity</span></p></body></html>", None))
        self.recipe_name_label.setText(_translate("MainWindow", "Recipe Name:", None))
        self.beer_type_label.setText(_translate("MainWindow", "Beer Type:", None))
        self.Batchnumber_label.setText(_translate("MainWindow", "Batch #:", None))
        self.efficiency_label.setText(_translate("MainWindow", "Exp. Efficiency:", None))
        self.Mash_schedule_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Mash Schedule -</span></p></body></html>", None))
        self.infusion_amount_label.setText(_translate("MainWindow", "<html><head/><body><p>Name / Infusion Amount</p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p>Temp</p></body></html>", None))
        self.Yeast_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Yeast -</span></p></body></html>", None))
        self.cost_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Cost -</span></p></body></html>", None))
        self.cost_grains_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Grains</span></p></body></html>", None))
        self.cost_hops_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Hops</span></p></body></html>", None))
        self.cost_yeast_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Yeast</span></p></body></html>", None))
        self.cost_other_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Other</span></p></body></html>", None))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p>Time</p></body></html>", None))
        self.yeast_starter_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Starter:</span></p></body></html>", None))
        self.yeast_type_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Type</span></p></body></html>", None))
        self.yeast_attenuation_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Avg Attenuation</span></p></body></html>", None))
        self.dollar_sign.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">$</span></p></body></html>", None))
        self.cost_total_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Total:</span></p></body></html>", None))
        self.notes_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Notes:</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.label_2.setText(_translate("MainWindow", "HLT  TEMP", None))
        self.label_3.setText(_translate("MainWindow", "MASH  TEMP", None))
        self.label_4.setText(_translate("MainWindow", "BOIL TEMP", None))
        self.label_5.setText(_translate("MainWindow", "CHILLER  TEMP", None))
        self.label_8.setText(_translate("MainWindow", "ALARM 1", None))
        self.HLT_alarm_set1.setText(_translate("MainWindow", "Set Alarm", None))
        self.HTL_Start.setText(_translate("MainWindow", "START TIMER", None))
        self.HLT_alarm_set1_2.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_9.setText(_translate("MainWindow", "ALARM 2", None))
        self.label_10.setText(_translate("MainWindow", "ALARM 3", None))
        self.HLT_alarm_set1_3.setText(_translate("MainWindow", "Set Alarm", None))
        self.label.setText(_translate("MainWindow", "HLT  TIMER", None))
        self.START_TIMER.setText(_translate("MainWindow", "START GRAPH", None))
        self.label_11.setText(_translate("MainWindow", "ALARM 4", None))
        self.HLT_alarm_set1_4.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_6.setText(_translate("MainWindow", "BOIL  TIMER", None))
        self.BOIL_TIMER_START_2.setText(_translate("MainWindow", "START TIMER", None))
        self.label_15.setText(_translate("MainWindow", "ALARM 1", None))
        self.Boil_alarm_set1.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_14.setText(_translate("MainWindow", "ALARM 2", None))
        self.Boil_alarm_set1_2.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_16.setText(_translate("MainWindow", "ALARM 3", None))
        self.Boil_alarm_set1_3.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_17.setText(_translate("MainWindow", "ALARM 4", None))
        self.Boil_alarm_set1_4.setText(_translate("MainWindow", "Set Alarm", None))
        self.HLT_alarm_set1_5.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_12.setText(_translate("MainWindow", "ALARM 5", None))
        self.Boil_alarm_set1_5.setText(_translate("MainWindow", "Set Alarm", None))
        self.label_13.setText(_translate("MainWindow", "ALARM 5", None))
        self.STOP_TIMER.setText(_translate("MainWindow", "STOP", None))
        self.RESET_TIMER.setText(_translate("MainWindow", "RESET", None))
        self.ALARM_RESET.setText(_translate("MainWindow", "ALARM RESET", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.Fermenter_two_label.setText(_translate("MainWindow", "Fermenter 2", None))
        self.cooler_temp_label.setText(_translate("MainWindow", "cooler Temp", None))
        self.fermenter_one_label.setText(_translate("MainWindow", "Fermenter 1", None))
        self.Fermenter_three_label.setText(_translate("MainWindow", "Fermenter 3", None))
        self.checkBox.setText(_translate("MainWindow", "cooler", None))
        self.checkBox_2.setText(_translate("MainWindow", "Fermenter 1", None))
        self.checkBox_3.setText(_translate("MainWindow", "Fermenter 2", None))
        self.checkBox_4.setText(_translate("MainWindow", "Fermenter 3", None))
        self.radioButton.setText(_translate("MainWindow", "Heater 1", None))
        self.radioButton_2.setText(_translate("MainWindow", "Heater 2", None))
        self.radioButton_3.setText(_translate("MainWindow", "Heater 3", None))
        self.Fermenter_three_label_2.setText(_translate("MainWindow", "Beer Label 3", None))
        self.fermenter_one_label_2.setText(_translate("MainWindow", "Beer Label 1", None))
        self.Fermenter_two_label_2.setText(_translate("MainWindow", "Beer Label 2", None))
        self.Fermenter_two_label_3.setText(_translate("MainWindow", "Date Start", None))
        self.fermenter_one_label_3.setText(_translate("MainWindow", "Date Start", None))
        self.Fermenter_three_label_3.setText(_translate("MainWindow", "Date Start", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Set Temprature Below</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

