# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Process_Control.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(917, 817)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.HLT_TEMP = QtGui.QLCDNumber(self.centralwidget)
        self.HLT_TEMP.setGeometry(QtCore.QRect(100, 120, 101, 51))
        self.HLT_TEMP.setObjectName(_fromUtf8("HLT_TEMP"))
        self.MASH_TEMP = QtGui.QLCDNumber(self.centralwidget)
        self.MASH_TEMP.setGeometry(QtCore.QRect(290, 120, 101, 51))
        self.MASH_TEMP.setObjectName(_fromUtf8("MASH_TEMP"))
        self.Boil_TEMP = QtGui.QLCDNumber(self.centralwidget)
        self.Boil_TEMP.setGeometry(QtCore.QRect(470, 120, 101, 51))
        self.Boil_TEMP.setObjectName(_fromUtf8("Boil_TEMP"))
        self.Chiller_Temp = QtGui.QLCDNumber(self.centralwidget)
        self.Chiller_Temp.setGeometry(QtCore.QRect(650, 120, 101, 51))
        self.Chiller_Temp.setObjectName(_fromUtf8("Chiller_Temp"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 270, 101, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 101, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 100, 101, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 100, 101, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 100, 101, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(740, 270, 101, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 270, 101, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(110, 364, 91, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(110, 440, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 510, 91, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(110, 590, 91, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(110, 670, 91, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.HTL_Start = QtGui.QPushButton(self.centralwidget)
        self.HTL_Start.setGeometry(QtCore.QRect(20, 320, 83, 24))
        self.HTL_Start.setObjectName(_fromUtf8("HTL_Start"))
        self.BOIL_TIMER_START = QtGui.QPushButton(self.centralwidget)
        self.BOIL_TIMER_START.setGeometry(QtCore.QRect(650, 320, 83, 24))
        self.BOIL_TIMER_START.setObjectName(_fromUtf8("BOIL_TIMER_START"))
        self.START_TIMER = QtGui.QPushButton(self.centralwidget)
        self.START_TIMER.setGeometry(QtCore.QRect(400, 300, 83, 24))
        self.START_TIMER.setObjectName(_fromUtf8("START_TIMER"))
        self.HLT_TIMER_SET = QtGui.QTimeEdit(self.centralwidget)
        self.HLT_TIMER_SET.setGeometry(QtCore.QRect(110, 310, 118, 41))
        self.HLT_TIMER_SET.setObjectName(_fromUtf8("HLT_TIMER_SET"))
        self.BOIL_TIMER_SET = QtGui.QTimeEdit(self.centralwidget)
        self.BOIL_TIMER_SET.setGeometry(QtCore.QRect(740, 310, 118, 41))
        self.BOIL_TIMER_SET.setObjectName(_fromUtf8("BOIL_TIMER_SET"))
        self.ALARM_HLT_1 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_HLT_1.setGeometry(QtCore.QRect(110, 390, 118, 41))
        self.ALARM_HLT_1.setObjectName(_fromUtf8("ALARM_HLT_1"))
        self.ALARM_HLT_2 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_HLT_2.setGeometry(QtCore.QRect(110, 460, 118, 41))
        self.ALARM_HLT_2.setObjectName(_fromUtf8("ALARM_HLT_2"))
        self.ALARM_HLT_3 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_HLT_3.setGeometry(QtCore.QRect(110, 530, 118, 41))
        self.ALARM_HLT_3.setObjectName(_fromUtf8("ALARM_HLT_3"))
        self.ALARM_HLT_4 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_HLT_4.setGeometry(QtCore.QRect(110, 610, 118, 41))
        self.ALARM_HLT_4.setObjectName(_fromUtf8("ALARM_HLT_4"))
        self.ALARM_HLT_5 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_HLT_5.setGeometry(QtCore.QRect(110, 690, 118, 41))
        self.ALARM_HLT_5.setObjectName(_fromUtf8("ALARM_HLT_5"))
        self.ALARM_BOIL_3 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_BOIL_3.setGeometry(QtCore.QRect(740, 530, 118, 41))
        self.ALARM_BOIL_3.setObjectName(_fromUtf8("ALARM_BOIL_3"))
        self.ALARM_BOIL_2 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_BOIL_2.setGeometry(QtCore.QRect(740, 460, 118, 41))
        self.ALARM_BOIL_2.setObjectName(_fromUtf8("ALARM_BOIL_2"))
        self.ALARM_BOIL_1 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_BOIL_1.setGeometry(QtCore.QRect(740, 390, 118, 41))
        self.ALARM_BOIL_1.setObjectName(_fromUtf8("ALARM_BOIL_1"))
        self.ALARM_BOIL_4 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_BOIL_4.setGeometry(QtCore.QRect(740, 610, 118, 41))
        self.ALARM_BOIL_4.setObjectName(_fromUtf8("ALARM_BOIL_4"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(740, 670, 91, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(740, 440, 91, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.ALARM_BOIL_5 = QtGui.QTimeEdit(self.centralwidget)
        self.ALARM_BOIL_5.setGeometry(QtCore.QRect(740, 690, 118, 41))
        self.ALARM_BOIL_5.setObjectName(_fromUtf8("ALARM_BOIL_5"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(740, 364, 91, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(740, 510, 91, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(740, 590, 91, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.HLT_alarm_set1 = QtGui.QCheckBox(self.centralwidget)
        self.HLT_alarm_set1.setGeometry(QtCore.QRect(20, 400, 84, 19))
        self.HLT_alarm_set1.setObjectName(_fromUtf8("HLT_alarm_set1"))
        self.HLT_alarm_set1_2 = QtGui.QCheckBox(self.centralwidget)
        self.HLT_alarm_set1_2.setGeometry(QtCore.QRect(20, 470, 84, 19))
        self.HLT_alarm_set1_2.setObjectName(_fromUtf8("HLT_alarm_set1_2"))
        self.HLT_alarm_set1_3 = QtGui.QCheckBox(self.centralwidget)
        self.HLT_alarm_set1_3.setGeometry(QtCore.QRect(20, 540, 84, 19))
        self.HLT_alarm_set1_3.setObjectName(_fromUtf8("HLT_alarm_set1_3"))
        self.HLT_alarm_set1_4 = QtGui.QCheckBox(self.centralwidget)
        self.HLT_alarm_set1_4.setGeometry(QtCore.QRect(20, 620, 84, 19))
        self.HLT_alarm_set1_4.setObjectName(_fromUtf8("HLT_alarm_set1_4"))
        self.HLT_alarm_set1_5 = QtGui.QCheckBox(self.centralwidget)
        self.HLT_alarm_set1_5.setGeometry(QtCore.QRect(20, 700, 84, 19))
        self.HLT_alarm_set1_5.setObjectName(_fromUtf8("HLT_alarm_set1_5"))
        self.Boil_alarm_set1 = QtGui.QCheckBox(self.centralwidget)
        self.Boil_alarm_set1.setGeometry(QtCore.QRect(650, 400, 84, 19))
        self.Boil_alarm_set1.setObjectName(_fromUtf8("Boil_alarm_set1"))
        self.Boil_alarm_set1_2 = QtGui.QCheckBox(self.centralwidget)
        self.Boil_alarm_set1_2.setGeometry(QtCore.QRect(650, 470, 84, 19))
        self.Boil_alarm_set1_2.setObjectName(_fromUtf8("Boil_alarm_set1_2"))
        self.Boil_alarm_set1_3 = QtGui.QCheckBox(self.centralwidget)
        self.Boil_alarm_set1_3.setGeometry(QtCore.QRect(650, 540, 84, 19))
        self.Boil_alarm_set1_3.setObjectName(_fromUtf8("Boil_alarm_set1_3"))
        self.Boil_alarm_set1_4 = QtGui.QCheckBox(self.centralwidget)
        self.Boil_alarm_set1_4.setGeometry(QtCore.QRect(650, 620, 84, 19))
        self.Boil_alarm_set1_4.setObjectName(_fromUtf8("Boil_alarm_set1_4"))
        self.Boil_alarm_set1_5 = QtGui.QCheckBox(self.centralwidget)
        self.Boil_alarm_set1_5.setGeometry(QtCore.QRect(650, 700, 84, 19))
        self.Boil_alarm_set1_5.setObjectName(_fromUtf8("Boil_alarm_set1_5"))
        self.HLT_Timer_DISPLAY = QtGui.QLCDNumber(self.centralwidget)
        self.HLT_Timer_DISPLAY.setGeometry(QtCore.QRect(100, 200, 131, 61))
        self.HLT_Timer_DISPLAY.setObjectName(_fromUtf8("HLT_Timer_DISPLAY"))
        self.TIMER_DISPLAY = QtGui.QLCDNumber(self.centralwidget)
        self.TIMER_DISPLAY.setGeometry(QtCore.QRect(370, 200, 151, 61))
        self.TIMER_DISPLAY.setObjectName(_fromUtf8("TIMER_DISPLAY"))
        self.BOIL_TIMER_DISPLAY = QtGui.QLCDNumber(self.centralwidget)
        self.BOIL_TIMER_DISPLAY.setGeometry(QtCore.QRect(720, 200, 131, 61))
        self.BOIL_TIMER_DISPLAY.setObjectName(_fromUtf8("BOIL_TIMER_DISPLAY"))
        self.STOP_TIMER = QtGui.QPushButton(self.centralwidget)
        self.STOP_TIMER.setGeometry(QtCore.QRect(400, 330, 83, 24))
        self.STOP_TIMER.setObjectName(_fromUtf8("STOP_TIMER"))
        self.RESET_TIMER = QtGui.QPushButton(self.centralwidget)
        self.RESET_TIMER.setGeometry(QtCore.QRect(400, 360, 83, 24))
        self.RESET_TIMER.setObjectName(_fromUtf8("RESET_TIMER"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 430, 291, 121))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.HLT_TEMP.raise_()
        self.MASH_TEMP.raise_()
        self.Boil_TEMP.raise_()
        self.Chiller_Temp.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.HTL_Start.raise_()
        self.BOIL_TIMER_START.raise_()
        self.START_TIMER.raise_()
        self.HLT_TIMER_SET.raise_()
        self.BOIL_TIMER_SET.raise_()
        self.ALARM_HLT_1.raise_()
        self.ALARM_HLT_2.raise_()
        self.ALARM_HLT_3.raise_()
        self.ALARM_HLT_4.raise_()
        self.ALARM_HLT_5.raise_()
        self.ALARM_BOIL_3.raise_()
        self.ALARM_BOIL_2.raise_()
        self.ALARM_BOIL_1.raise_()
        self.ALARM_BOIL_4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.ALARM_BOIL_5.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.HLT_alarm_set1.raise_()
        self.HLT_alarm_set1_2.raise_()
        self.HLT_alarm_set1_3.raise_()
        self.HLT_alarm_set1_4.raise_()
        self.HLT_alarm_set1_5.raise_()
        self.Boil_alarm_set1.raise_()
        self.Boil_alarm_set1_2.raise_()
        self.Boil_alarm_set1_3.raise_()
        self.Boil_alarm_set1_4.raise_()
        self.Boil_alarm_set1_5.raise_()
        self.HLT_Timer_DISPLAY.raise_()
        self.TIMER_DISPLAY.raise_()
        self.BOIL_TIMER_DISPLAY.raise_()
        self.STOP_TIMER.raise_()
        self.RESET_TIMER.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "HLT  TIMER", None))
        self.label_2.setText(_translate("MainWindow", "HLT  TEMP", None))
        self.label_3.setText(_translate("MainWindow", "MASH  TEMP", None))
        self.label_4.setText(_translate("MainWindow", "BOIL TEMP", None))
        self.label_5.setText(_translate("MainWindow", "CHILLER  TEMP", None))
        self.label_6.setText(_translate("MainWindow", "BOIL  TIMER", None))
        self.label_7.setText(_translate("MainWindow", "Stop Watch", None))
        self.label_8.setText(_translate("MainWindow", "ALARM 1", None))
        self.label_9.setText(_translate("MainWindow", "ALARM 2", None))
        self.label_10.setText(_translate("MainWindow", "ALARM 3", None))
        self.label_11.setText(_translate("MainWindow", "ALARM 4", None))
        self.label_12.setText(_translate("MainWindow", "ALARM 5", None))
        self.HTL_Start.setText(_translate("MainWindow", "SET TIMER", None))
        self.BOIL_TIMER_START.setText(_translate("MainWindow", "SET TIMER", None))
        self.START_TIMER.setText(_translate("MainWindow", "START", None))
        self.label_13.setText(_translate("MainWindow", "ALARM 5", None))
        self.label_14.setText(_translate("MainWindow", "ALARM 2", None))
        self.label_15.setText(_translate("MainWindow", "ALARM 1", None))
        self.label_16.setText(_translate("MainWindow", "ALARM 3", None))
        self.label_17.setText(_translate("MainWindow", "ALARM 4", None))
        self.HLT_alarm_set1.setText(_translate("MainWindow", "Alarm set", None))
        self.HLT_alarm_set1_2.setText(_translate("MainWindow", "Alarm set", None))
        self.HLT_alarm_set1_3.setText(_translate("MainWindow", "Alarm set", None))
        self.HLT_alarm_set1_4.setText(_translate("MainWindow", "Alarm set", None))
        self.HLT_alarm_set1_5.setText(_translate("MainWindow", "Alarm set", None))
        self.Boil_alarm_set1.setText(_translate("MainWindow", "Alarm set", None))
        self.Boil_alarm_set1_2.setText(_translate("MainWindow", "Alarm set", None))
        self.Boil_alarm_set1_3.setText(_translate("MainWindow", "Alarm set", None))
        self.Boil_alarm_set1_4.setText(_translate("MainWindow", "Alarm set", None))
        self.Boil_alarm_set1_5.setText(_translate("MainWindow", "Alarm set", None))
        self.STOP_TIMER.setText(_translate("MainWindow", "STOP", None))
        self.RESET_TIMER.setText(_translate("MainWindow", "RESET", None))
        self.pushButton.setText(_translate("MainWindow", "ALARM RESET", None))

